### ISSUE TITLE
berokka conda install has an issue with the Bio::SeqIO perl module

### ISSUE THREAD

**Issue by Koen-vdl** [tseemann/berokka#26]
My conda install produces the following error:

` berokka
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /home/kvandelannoo/miniconda3/envs/berokka_env/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/kvandelannoo/miniconda3/envs/berokka_env/lib/site_perl/5.26.2 /home/kvandelannoo/miniconda3/envs/berokka_env/lib/5.26.2/x86_64-linux-thread-multi /home/kvandelannoo/miniconda3/envs/berokka_env/lib/5.26.2 .) at /home/kvandelannoo/miniconda3/envs/berokka_env/bin/berokka line 4.
BEGIN failed--compilation aborted at /home/kvandelannoo/miniconda3/envs/berokka_env/bin/berokka line 4.`

I installed berokka using:
`conda install -c conda-forge -c bioconda -c defaults berokka`

I tried the following things without success:
1/ updating conda
2/ creating a separate conda env 

My install looks OK to me:

```
which berokka
~/miniconda3/envs/berokka_env/bin/berokka

which perl
~/miniconda3/envs/berokka_env/bin/perl

echo $PATH | tr ":" "\n" | nl
 1  /home/kvandelannoo/miniconda3/envs/berokka_env/bin
     2  /home/kvandelannoo/miniconda3/condabin
     3  /usr/local/showq/0.15/bin
     4  /usr/local/slurm/latest/bin
     5  /usr/lib64/qt-3.3/bin
     6  /usr/local/bin
     7  /usr/bin
     8  /usr/local/sbin
     9  /usr/sbin
    10  /opt/ibutils/bin
    11  /opt/puppetlabs/bin
    12  /opt/dell/srvadmin/bin
    13  /home/kvandelannoo/.local/bin
    14  /home/kvandelannoo/bin

 perl -e "print qq(@INC)"
/home/kvandelannoo/miniconda3/envs/berokka_env/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/kvandelannoo/miniconda3/envs/berokka_env/lib/site_perl/5.26.2 /home/kvandelannoo/miniconda3/envs/berokka_env/lib/5.26.2/x86_64-linux-thread-multi /home/kvandelannoo/miniconda3/envs/berokka_env/lib/5.26.2
```

Any help with this would be much appreciated. 

KV

**Comment by tseemann** [comment]
This is fixed now I think!

https://github.com/bioconda/bioconda-recipes/pull/20286
