### ISSUE TITLE
Error: NCBI C++ Exception:

### ISSUE THREAD

**Issue by bitcometz** [tseemann/berokka#27]
hello，
 I used conda to install berokka, but run into this problem:

Error: NCBI C++ Exception:
    T0 "/opt/conda/conda-bld/blast_1537407096784/work/c++/src/objtools/readers/fasta.cpp", line 2178: Error: ncbi::objects::CFastaReader::PostWarning() - CFastaReader: Near line 7, there's a line that doesn't look like plausible data, but it's not marked as defline or comment. (m_Pos = 7

Thanks!!!!

**Comment by tseemann** [comment]
Your installation of BLAST is broken.
Try `conda update --all --yes`
Otherwise I am unable to assist.
